site_name: Pigs Are Pink - Policies

theme:
  name: material
  logo: https://pigsare.pink/assets/openmoji-pig.svg
  favicon: https://pigsare.pink/assets/openmoji-pig.svg
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode