site_name: Pigs Are Pink - Policies
copyright: Copyright &copy; 2024 Asa Masterson
extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/asa-masterson/md_policies

theme:
  name: material
  logo: https://pigsare.pink/assets/openmoji-pig.svg
  favicon: https://pigsare.pink/assets/openmoji-pig.svg
  features:
    - navigation.footer
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode